language: ruby
rvm:
- 2.2
deploy:
  provider: heroku
  api_key:
    secure: Y6q010zuZAMV6rXVd4bCkgx+E6rPE8lvfCdXvzalJbQlvaBQRRj68eSlVchjHVH9qm6KsJKbH5SdGJjEiBkcCXFR30tyr+zq+avWJ3tEZNdn6vjsDNH7WlT0FznoHvM/ZSBNr50k4d17S78i589sLG0FxQo37ZoiApPariiF98Kf59EKqfcUfthIZVa425AqNTGPQ4cDw/e+J7CwGmbd/TeYON+EpU7qdvK9bvn6kNyjG2BvYCCsmZ6l57Daq9pcfsK0Rje1DwPvx9BPI3UFQwnAokAbkVf0O0bLPEh0aQBKdt7vmru1AC8QWmnK8LypWWZ2uA/6vAw8wiPZYDLjzatxsN6FvZOz0Qfx5+4LZd1dq/ohFH/FWUPxORYdJHiuOT8lJJuzkSsEiP/S6yNAN3M/hkF02CkZU8q46zO0AWOlM1DEe/GkDrWUfbTkjOPUJyb9pmXH37kEnE0WJGdQLHdfxWbhHaeyDzuHaue+hxXJxslfoQbg3tX5BUi7HV5URDZBNqdA5Q+XKtJ7IF4CDmRLMDDoMB/5M6vNcTqXDSvVmCFAivwfGBenaPUziMyOuKhvM9gldffXE/jnvc38VH7BYV+gJBXWLUrvl17TSbwM3IPmd05ETHKboJjAdFervFc9XvAp64jlgZ9w/KveWhCZntuWl50XTKSvn+/IIFQ=
  app: webintegrale
  on:
    repo: Integrale18/projetlpa
